---
title: "Pete Moore"
subtitle: "Data Scientist"
author: "Pete Moore"
date: "`r Sys.Date()`"
output:
  tufte::tufte_html: default
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_book:
    citation_package: natbib
    latex_engine: xelatex
bibliography: CV.bib
link-citations: yes
---

```{r r-dev-enviroment, include = FALSE}
#####keep R tidy#####
options(warn=-1)
rm(list=ls()) #clear variables
cat("\014")  #clear console
```

```{r r-setup-part-1, include=FALSE} 
# we are going to use R, sql and python and we are going to set them up now.

# use the tufte library for visual output
require(tufte)

# use the reticulate library to speak to python
library(reticulate)

# and immediately deploy reticulate to utilise conda
use_condaenv(condaenv="PyR", required =TRUE)

```

```{python py-setup, include=FALSE}
# Internal variables setup (NB set up variables in python so can be passed to R)
editid = 2 #an id for this edit of the cv; set o zero to build new edit

# we want to utilise the included to build a model for thisCV 
PATH_FILE="/Users/petermoore/Documents/GitHub/Pete Moore - Data Scientist - CV/Python"
import os
os.chdir(PATH_FILE)
import sys
sys.path.append(PATH_FILE) #add local directory to path

# get constants from bespke pytong scpript
import constants
from constants import DSN, ALCHEMYDSN, pdsn, puser, ppassword

if editid == 0:
  import BuildSQLDataModel
  editid = BuildSQLDataModel.buildEdit(1)
  print("most recent editid is: " + str(editid)) #<-- note to self, you are still in python so paste won't work!


```

```{r r-setup-part-2, include=FALSE} 
# use the DBI and odbc packages to connet to sql from R
#(NB the exact connections.yaml file is not included, for obvious password-related reasons, but I've provided a mock-up in the ODBC folder which you could adapt)
library(DBI) # for SQL database calls
library(odbc) # for R database calls

# get connection variables 
con <- DBI::dbConnect(odbc::odbc(),
                      DSN = py$pdsn,
                      uid = py$puser,
                      pwd = py$ppassword)

# collate these in knitr with all the other chunk options
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tufte'), connection = "con", max.print = NA, fig.cap = TRUE) 
knitr::knit_engines$set(python = reticulate::eng_python)

# set up html
options(htmltools.dir.version = FALSE)

```


# Curriculum Vitae
```{r r-sections, eval=TRUE, echo=FALSE}
section.sql <- "dbo.usp_PM_Section_GetSections"
section.query <- dbSendQuery(con, section.sql)
section.list <- dbFetch(section.query)

for (i in section.list){
  cat("  \n###",  i, "Air Quaility  \n")
  #print(plot(airquality[airquality$Month == i,]))
  print("some text")
  cat("  \n")
  
}
```

```{r r-bullet, echo = FALSE}
makebullet <- function(s){
  y <- paste("\n
* ", s)
  return(y)
}
```
What about `r makebullet("bullet")` <-this?

# Bibiliography
```{r bib, include=FALSE}
# create a bib file for the R packages used in this document
knitr::write_bib(c('base', 'rmarkdown'), file = '.bib')
```


# Appendix 0: SQL Tables
```{python, echo=FALSE, eval=TRUE, comment =""}
# sample pyodbc statement
from datalib import sqldf
df1 = sqldf(sql="SELECT [name] FROM sys.tables", con=DSN)
#NB Python datbase access via pyodbc on which you can read more here: https://github.com/mkleehammer/pyodbc/wiki/Connecting-to-SQL-Server-from-Mac-OSX
print(df1)
```
# Appendix 1: SQL Server Version
```{sql, echo=FALSE, eval=TRUE}
-- sample SQL statement
SELECT @@VERSION
```
